"use client";

import { useState, type ReactNode } from "react";
import { Controller, useForm, type Control } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { ArrowLeft, ArrowRight, Check, RefreshCw, Trash2 } from "lucide-react";

import { Button } from "@/components/ui/button";
import { DateField } from "@/components/ui/date-picker";
import { FieldGroup, FullWidth } from "@/components/ui/field-group";
import { FormField } from "@/components/ui/form-field";
import { CountrySelect } from "@/components/ui/geo-selects";
import { OptionSelect } from "@/components/ui/option-select";
import { Sheet, SheetContent, SheetTrigger } from "@/components/ui/sheet";
import { cn } from "@/lib/utils";
import { ApiError } from "@/lib/api";
import { generatePassword, generateUniqueId, normalizeUniqueId } from "@/lib/generate";
import { CompanySelect, StoreSelect, SupervisorSelect } from "@/components/org/entity-selects";
import { useCompanies } from "@/features/org/companies";
import { useStores } from "@/features/org/stores";
import {
  useCreateEmployee,
  useSupervisors,
  useUpdateEmployee,
} from "@/features/employees/employees";
import { useCurrentUser } from "@/features/session/use-current-user";
import {
  BENEFIT_OPTIONS,
  CONTRACT_TYPE_OPTIONS,
  EMPLOYEE_STATUS_OPTIONS,
  GENDER_OPTIONS,
  MARITAL_STATUS_OPTIONS,
  WORK_SCHEDULE_OPTIONS,
} from "@/features/employees/constants";
import type { EmployeeBenefits, EmployeeDetail } from "@/features/employees/types";

const schema = z.object({
  // Step 1 — main data
  firstName: z.string().min(1, "Required"),
  lastName: z.string().min(1, "Required"),
  email: z.string().email("Invalid email").optional().or(z.literal("")),
  phone: z.string().optional(),
  nationality: z.string().optional(),
  dateOfBirth: z.string().optional(),
  gender: z.enum(["male", "female", "other", "prefer_not_to_say"]).optional().or(z.literal("")),
  maritalStatus: z
    .enum(["single", "married", "divorced", "widowed", "other"])
    .optional()
    .or(z.literal("")),
  idCardNumber: z.string().optional(),
  country: z.string().optional(),
  state: z.string().optional(),
  city: z.string().optional(),
  postalCode: z.string().optional(),
  address: z.string().optional(),
  iban: z.string().optional(),
  // Step 2 — contractual
  role: z.string().optional(),
  companyEmail: z.string().email("Invalid email").optional().or(z.literal("")),
  status: z.enum(["active", "invited", "on_leave", "suspended", "archived"]).optional(),
  workScheduleType: z
    .enum(["full_time", "part_time", "shift", "flexible", "remote"])
    .optional()
    .or(z.literal("")),
  weeklyHours: z
    .string()
    .optional()
    .refine((v) => !v || (Number(v) >= 0 && Number(v) <= 168), "0–168"),
  hireDate: z.string().optional(),
  contractEnd: z.string().optional(),
  contractType: z
    .enum(["full_time", "part_time", "temporary", "contractor", "intern"])
    .optional()
    .or(z.literal("")),
});
type Values = z.infer<typeof schema>;

const STEPS = [
  { label: "Main Data", hint: "Identity, address & ID" },
  { label: "Contractual Details", hint: "Role, contract & benefits" },
];

/** Fields validated on step 1 — gate "Next" on these. */
const STEP1_FIELDS = ["firstName", "lastName", "email"] as const;

export function EmployeeFormSheet({
  employee,
  trigger,
  open: openProp,
  onOpenChange,
  onDelete,
}: {
  employee?: EmployeeDetail;
  trigger?: ReactNode;
  open?: boolean;
  onOpenChange?: (open: boolean) => void;
  /** Edit mode only: open the delete modal (rendered by the parent). */
  onDelete?: () => void;
}) {
  const isEdit = Boolean(employee);
  const [openState, setOpenState] = useState(false);
  const open = openProp ?? openState;
  const setOpen = (next: boolean) => {
    setOpenState(next);
    onOpenChange?.(next);
  };
  const [step, setStep] = useState(0);
  const [serverError, setServerError] = useState<string | null>(null);
  const [primaryStoreId, setPrimaryStoreId] = useState<string | undefined>(
    employee?.primaryStoreId ?? undefined,
  );
  const [supervisorId, setSupervisorId] = useState<string | undefined>(
    employee?.supervisorId ?? undefined,
  );
  const [benefits, setBenefits] = useState<EmployeeBenefits>(employee?.benefits ?? {});
  // Unique ID + password — autogenerated, editable, regenerable (P14).
  const [uniqueId, setUniqueId] = useState(() => employee?.uniqueCode ?? generateUniqueId());
  const [password, setPassword] = useState(() => (employee ? "" : generatePassword()));

  const { data: stores } = useStores();
  const { data: companies } = useCompanies();
  const { data: supervisors } = useSupervisors();
  const { data: me } = useCurrentUser();
  const createEmployee = useCreateEmployee();
  const updateEmployee = useUpdateEmployee(employee?.id ?? "");

  const {
    register,
    handleSubmit,
    reset,
    control,
    trigger: validate,
    formState: { errors, isSubmitting },
  } = useForm<Values>({
    resolver: zodResolver(schema),
    defaultValues: {
      firstName: employee?.firstName ?? "",
      lastName: employee?.lastName ?? "",
      email: employee?.email ?? "",
      phone: employee?.phone ?? "",
      nationality: employee?.nationality ?? "",
      dateOfBirth: employee?.dateOfBirth ?? "",
      gender: employee?.gender ?? "",
      maritalStatus: employee?.maritalStatus ?? "",
      idCardNumber: employee?.idCardNumber ?? "",
      country: employee?.country ?? "",
      state: employee?.state ?? "",
      city: employee?.city ?? "",
      postalCode: employee?.postalCode ?? "",
      address: employee?.address ?? "",
      iban: employee?.iban ?? "",
      role: employee?.role ?? "",
      companyEmail: employee?.companyEmail ?? "",
      status: employee?.status ?? "active",
      workScheduleType: employee?.workScheduleType ?? "",
      weeklyHours: employee?.weeklyHours != null ? String(employee.weeklyHours) : "",
      hireDate: employee?.hireDate ?? "",
      contractEnd: employee?.contractEnd ?? "",
      contractType: employee?.contractType ?? "",
    },
  });

  const activeCompanyId = me?.companyId ?? companies?.[0]?.id;

  const resetAll = () => {
    reset();
    setStep(0);
    setPrimaryStoreId(employee?.primaryStoreId ?? undefined);
    setSupervisorId(employee?.supervisorId ?? undefined);
    setBenefits(employee?.benefits ?? {});
    setUniqueId(employee?.uniqueCode ?? generateUniqueId());
    setPassword(employee ? "" : generatePassword());
    setServerError(null);
  };

  const goNext = async () => {
    const ok = await validate(STEP1_FIELDS);
    if (ok) setStep(1);
  };

  const toggleBenefit = (key: string) => setBenefits((b) => ({ ...b, [key]: !b[key] }));

  // The REAL persist — only ever invoked from the final step's submit button.
  const onSubmit = async (values: Values) => {
    setServerError(null);
    const payload = {
      firstName: values.firstName,
      lastName: values.lastName,
      email: values.email || undefined,
      phone: values.phone || undefined,
      companyEmail: values.companyEmail || undefined,
      nationality: values.nationality || undefined,
      dateOfBirth: values.dateOfBirth || undefined,
      gender: values.gender || undefined,
      maritalStatus: values.maritalStatus || undefined,
      idCardNumber: values.idCardNumber || undefined,
      iban: values.iban || undefined,
      country: values.country || undefined,
      state: values.state || undefined,
      city: values.city || undefined,
      postalCode: values.postalCode || undefined,
      address: values.address || undefined,
      role: values.role || undefined,
      status: values.status,
      workScheduleType: values.workScheduleType || undefined,
      weeklyHours: values.weeklyHours ? Number(values.weeklyHours) : undefined,
      hireDate: values.hireDate || undefined,
      contractEnd: values.contractEnd || undefined,
      contractType: values.contractType || undefined,
      primaryStoreId: primaryStoreId || undefined,
      supervisorId: supervisorId || undefined,
      benefits: Object.keys(benefits).length ? benefits : undefined,
      uniqueCode: uniqueId || undefined,
    };
    try {
      if (isEdit) await updateEmployee.mutateAsync(payload);
      else await createEmployee.mutateAsync(payload);
      setOpen(false);
      resetAll();
    } catch (error) {
      setServerError(error instanceof ApiError ? error.message : "Something went wrong.");
      setStep(1);
    }
  };

  // Guard: the form's submit handler. On step 0 it advances (never creates),
  // so pressing Enter in a step-1 field can NEVER create a half-filled employee.
  const handleFormSubmit = (e: React.FormEvent) => {
    if (step === 0) {
      e.preventDefault();
      void goNext();
      return;
    }
    void handleSubmit(onSubmit)(e);
  };

  return (
    <Sheet
      open={open}
      onOpenChange={(o) => {
        setOpen(o);
        if (!o) resetAll();
      }}
    >
      {trigger ? <SheetTrigger render={trigger as React.ReactElement} /> : null}
      <SheetContent
        showCloseButton={false}
        className="flex w-full flex-col gap-0 p-0 sm:max-w-3xl"
      >
        {/* Header — title + small subtext + step rail (heading UNDER the number). */}
        <div className="border-b border-border bg-linear-to-br from-accent-soft via-surface to-surface px-6 pt-4 pb-4">
          <h2 className="font-display text-lg font-semibold text-foreground">
            {isEdit ? "Edit Employee" : "New Employee"}
          </h2>
          <p className="mt-0.5 text-xs text-muted-foreground">
            {isEdit
              ? "Update this person's main data and contractual details."
              : "Add a person to your directory — main data, then contractual details."}
          </p>
          <StepRail steps={STEPS} current={step} onStep={setStep} />
        </div>

        <form onSubmit={handleFormSubmit} className="flex min-h-0 flex-1 flex-col" noValidate>
          <div className="scrollbar-none flex-1 space-y-6 overflow-y-auto px-6 py-5">
            {step === 0 ? (
              <>
                <FieldGroup title="Main data">
                  <FormField
                    id="firstName"
                    label="First name"
                    error={errors.firstName?.message}
                    {...register("firstName")}
                  />
                  <FormField
                    id="lastName"
                    label="Last name"
                    error={errors.lastName?.message}
                    {...register("lastName")}
                  />
                  <FormField
                    id="email"
                    label="Email"
                    type="email"
                    error={errors.email?.message}
                    {...register("email")}
                  />
                  <FormField id="phone" label="Phone" {...register("phone")} />
                  <FullWidth>
                    <UniqueIdField
                      value={uniqueId}
                      onChange={setUniqueId}
                      onRegenerate={() => setUniqueId(generateUniqueId())}
                    />
                  </FullWidth>
                </FieldGroup>

                <FieldGroup title="Personal information">
                  <FormField id="nationality" label="Nationality" {...register("nationality")} />
                  <Controller
                    control={control}
                    name="dateOfBirth"
                    render={({ field }) => (
                      <DateField
                        id="dateOfBirth"
                        label="Date of birth"
                        value={field.value ?? ""}
                        onChange={field.onChange}
                      />
                    )}
                  />
                  <ControlledSelect
                    control={control}
                    name="gender"
                    label="Gender"
                    options={GENDER_OPTIONS}
                  />
                  <ControlledSelect
                    control={control}
                    name="maritalStatus"
                    label="Marital status"
                    options={MARITAL_STATUS_OPTIONS}
                  />
                  <FullWidth>
                    <FormField
                      id="idCardNumber"
                      label="ID card number"
                      placeholder="National ID / passport no."
                      {...register("idCardNumber")}
                    />
                  </FullWidth>
                </FieldGroup>

                <FieldGroup title="Address">
                  <Controller
                    control={control}
                    name="country"
                    render={({ field }) => (
                      <Field label="Country">
                        <CountrySelect value={field.value || undefined} onChange={field.onChange} />
                      </Field>
                    )}
                  />
                  <FormField id="state" label="State / region" {...register("state")} />
                  <FormField id="city" label="City" {...register("city")} />
                  <FormField id="postalCode" label="Postal code" {...register("postalCode")} />
                  <FullWidth>
                    <FormField id="address" label="Address" {...register("address")} />
                  </FullWidth>
                </FieldGroup>

                <FieldGroup title="Banking & accounts">
                  <FullWidth>
                    <FormField
                      id="iban"
                      label="IBAN"
                      placeholder="GB29 NWBK 6016 1331 9268 19"
                      {...register("iban")}
                    />
                  </FullWidth>
                  {isEdit ? (
                    <FullWidth>
                      <p className="text-xs text-muted-foreground">
                        Manage additional bank accounts from the employee&apos;s profile.
                      </p>
                    </FullWidth>
                  ) : null}
                </FieldGroup>
              </>
            ) : (
              <>
                <FieldGroup title="Platform information">
                  <FullWidth>
                    <Field label="Company">
                      <CompanySelect
                        companies={companies}
                        value={activeCompanyId}
                        onChange={() => undefined}
                        disabled
                      />
                    </Field>
                  </FullWidth>
                  <Field label="Primary store">
                    <StoreSelect
                      stores={stores}
                      companies={companies}
                      value={primaryStoreId}
                      onChange={setPrimaryStoreId}
                    />
                  </Field>
                  <Field label="Supervisor">
                    <SupervisorSelect
                      supervisors={supervisors}
                      value={supervisorId}
                      onChange={setSupervisorId}
                    />
                  </Field>
                  <FormField id="role" label="Job role" placeholder="Barista" {...register("role")} />
                  <ControlledSelect
                    control={control}
                    name="status"
                    label="Status"
                    options={EMPLOYEE_STATUS_OPTIONS}
                  />
                  <FullWidth>
                    <FormField
                      id="companyEmail"
                      label="Company email"
                      type="email"
                      error={errors.companyEmail?.message}
                      {...register("companyEmail")}
                    />
                  </FullWidth>
                  {!isEdit ? (
                    <FullWidth>
                      <PasswordField
                        value={password}
                        onChange={setPassword}
                        onRegenerate={() => setPassword(generatePassword())}
                      />
                    </FullWidth>
                  ) : null}
                </FieldGroup>

                <FieldGroup title="Contract information">
                  <ControlledSelect
                    control={control}
                    name="workScheduleType"
                    label="Work schedule"
                    options={WORK_SCHEDULE_OPTIONS}
                  />
                  <FormField
                    id="weeklyHours"
                    type="number"
                    label="Weekly hours"
                    error={errors.weeklyHours?.message}
                    {...register("weeklyHours")}
                  />
                  <Controller
                    control={control}
                    name="hireDate"
                    render={({ field }) => (
                      <DateField
                        id="hireDate"
                        label="Hire date"
                        value={field.value ?? ""}
                        onChange={field.onChange}
                      />
                    )}
                  />
                  <Controller
                    control={control}
                    name="contractEnd"
                    render={({ field }) => (
                      <DateField
                        id="contractEnd"
                        label="Contract end"
                        value={field.value ?? ""}
                        onChange={field.onChange}
                      />
                    )}
                  />
                  <FullWidth>
                    <ControlledSelect
                      control={control}
                      name="contractType"
                      label="Contract type"
                      options={CONTRACT_TYPE_OPTIONS}
                    />
                  </FullWidth>
                </FieldGroup>

                <FieldGroup title="Benefits">
                  <FullWidth>
                    <div className="grid grid-cols-2 gap-2">
                      {BENEFIT_OPTIONS.map((b) => {
                        const on = Boolean(benefits[b.key]);
                        return (
                          <button
                            key={b.key}
                            type="button"
                            onClick={() => toggleBenefit(b.key)}
                            className={cn(
                              "flex items-center gap-2 rounded-lg border px-3 py-2 text-left text-sm transition-colors",
                              on
                                ? "border-primary bg-accent-soft text-foreground"
                                : "border-border bg-surface text-muted-foreground hover:border-foreground/20",
                            )}
                          >
                            <span
                              className={cn(
                                "flex size-4.5 shrink-0 items-center justify-center rounded-md border transition-colors",
                                on ? "border-primary bg-primary text-primary-foreground" : "border-border",
                              )}
                            >
                              {on ? <Check className="size-3" /> : null}
                            </span>
                            {b.label}
                          </button>
                        );
                      })}
                    </div>
                  </FullWidth>
                </FieldGroup>
              </>
            )}

            {serverError ? <p className="text-sm text-destructive">{serverError}</p> : null}
          </div>

          {/* Footer — delete (left, edit only) · Cancel + Back/Next/Save (right). */}
          <div className="flex items-center justify-between gap-2 border-t border-border bg-surface-subtle/60 px-6 py-3">
            <div>
              {isEdit && onDelete ? (
                <Button
                  type="button"
                  variant="ghost"
                  onClick={onDelete}
                  className="text-destructive hover:bg-destructive/10 hover:text-destructive"
                >
                  <Trash2 />
                  Delete
                </Button>
              ) : null}
            </div>
            <div className="flex items-center gap-2">
              {step === 0 ? (
                <Button type="button" variant="outline" onClick={() => setOpen(false)}>
                  Cancel
                </Button>
              ) : (
                <Button type="button" variant="outline" onClick={() => setStep(0)}>
                  <ArrowLeft />
                  Back
                </Button>
              )}
              {step === 0 ? (
                <Button type="button" onClick={goNext}>
                  Next
                  <ArrowRight />
                </Button>
              ) : (
                <Button type="submit" disabled={isSubmitting}>
                  {isSubmitting ? "Saving…" : isEdit ? "Save changes" : "Create employee"}
                </Button>
              )}
            </div>
          </div>
        </form>
      </SheetContent>
    </Sheet>
  );
}

/** Step rail: numbered circles with the heading + tiny subtext UNDER each, a
 * connector line between that fills as you progress (P14). */
function StepRail({
  steps,
  current,
  onStep,
}: {
  steps: { label: string; hint: string }[];
  current: number;
  onStep: (i: number) => void;
}) {
  return (
    <ol className="mt-4 flex items-start">
      {steps.map((s, i) => {
        const done = i < current;
        const active = i === current;
        const isLast = i === steps.length - 1;
        return (
          <li
            key={s.label}
            className={cn("flex flex-col", isLast ? "flex-none" : "flex-1")}
          >
            {/* Row: centered number + connector to the next step. */}
            <div className="flex items-center">
              <button
                type="button"
                disabled={i > current}
                onClick={() => i < current && onStep(i)}
                className={cn(
                  "mx-auto flex size-9 shrink-0 items-center justify-center rounded-full border-2 text-sm font-semibold transition-all",
                  active &&
                    "border-primary bg-primary text-primary-foreground shadow-[0_0_0_4px_rgb(var(--accent-soft))]",
                  done && "border-primary bg-accent-soft text-primary",
                  !active && !done && "border-border bg-surface text-muted-foreground",
                )}
              >
                {done ? <Check className="size-4" /> : i + 1}
              </button>
              {!isLast ? (
                <span
                  className={cn(
                    "-mx-4 h-0.5 flex-1 rounded-full transition-colors",
                    i < current ? "bg-primary" : "bg-border",
                  )}
                />
              ) : null}
            </div>
            {/* Heading + hint, CENTER-aligned under the number. */}
            <div className={cn("mt-1.5 px-1 text-center", isLast ? "w-9" : "")}>
              <p
                className={cn(
                  "text-xs font-semibold whitespace-nowrap",
                  active || done ? "text-foreground" : "text-muted-foreground",
                )}
              >
                {s.label}
              </p>
              <p className="text-[10px] leading-tight whitespace-nowrap text-muted-foreground">
                {s.hint}
              </p>
            </div>
          </li>
        );
      })}
    </ol>
  );
}

/** Unique-ID field: uppercase-normalized input + "Generate new ID" text button. */
function UniqueIdField({
  value,
  onChange,
  onRegenerate,
}: {
  value: string;
  onChange: (v: string) => void;
  onRegenerate: () => void;
}) {
  return (
    <div className="space-y-1.5">
      <div className="flex items-center justify-between">
        <label htmlFor="uniqueId" className="text-[13px] font-medium text-foreground">
          Unique ID
        </label>
        <button
          type="button"
          onClick={onRegenerate}
          className="inline-flex items-center gap-1 text-xs font-medium text-primary hover:text-accent-strong"
        >
          <RefreshCw className="size-3" />
          Generate new ID
        </button>
      </div>
      <input
        id="uniqueId"
        value={value}
        onChange={(e) => onChange(normalizeUniqueId(e.target.value))}
        className="h-9 w-full rounded-lg border border-border bg-background px-3 text-sm font-mono tracking-wide text-foreground uppercase outline-none transition-colors focus-visible:border-ring focus-visible:ring-3 focus-visible:ring-ring/50"
        placeholder="ABC-123"
      />
    </div>
  );
}

/** Password field with a regenerate button (autogenerated, editable). */
function PasswordField({
  value,
  onChange,
  onRegenerate,
}: {
  value: string;
  onChange: (v: string) => void;
  onRegenerate: () => void;
}) {
  return (
    <div className="space-y-1.5">
      <div className="flex items-center justify-between">
        <label htmlFor="genPassword" className="text-[13px] font-medium text-foreground">
          Temporary password
        </label>
        <button
          type="button"
          onClick={onRegenerate}
          className="inline-flex items-center gap-1 text-xs font-medium text-primary hover:text-accent-strong"
        >
          <RefreshCw className="size-3" />
          Regenerate
        </button>
      </div>
      <input
        id="genPassword"
        value={value}
        onChange={(e) => onChange(e.target.value)}
        className="h-9 w-full rounded-lg border border-border bg-background px-3 font-mono text-sm text-foreground outline-none transition-colors focus-visible:border-ring focus-visible:ring-3 focus-visible:ring-ring/50"
        placeholder="Auto-generated"
      />
    </div>
  );
}

/** Small labeled wrapper for non-input controls (rich selects). */
function Field({ label, children }: { label: string; children: ReactNode }) {
  return (
    <div className="space-y-1.5">
      <label className="text-[13px] font-medium text-foreground">{label}</label>
      {children}
    </div>
  );
}

/** Labeled, RHF-controlled themed dropdown (OptionSelect) for the modal. */
function ControlledSelect({
  control,
  name,
  label,
  options,
  placeholder = "—",
}: {
  control: Control<Values>;
  name: keyof Values;
  label: string;
  options: { value: string; label: string }[];
  placeholder?: string;
}) {
  return (
    <Field label={label}>
      <Controller
        control={control}
        name={name}
        render={({ field }) => (
          <OptionSelect
            value={(field.value as string) || undefined}
            onChange={field.onChange}
            options={options}
            placeholder={placeholder}
          />
        )}
      />
    </Field>
  );
}
