"use client";

import { useState, type ReactNode } from "react";
import { Controller, useForm, type Control } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { ArrowLeft, ArrowRight, ArrowRightLeft, Check, RefreshCw, ShieldCheck, Trash2, X } from "lucide-react";

import { Button } from "@/components/ui/button";
import { DateField } from "@/components/ui/date-picker";
import { FieldGroup, FullWidth } from "@/components/ui/field-group";
import { FormField } from "@/components/ui/form-field";
import { CountrySelect } from "@/components/ui/geo-selects";
import { OptionSelect } from "@/components/ui/option-select";
import { RoleTag } from "@/components/ui/role-tag";
import { Sheet, SheetContent, SheetTrigger } from "@/components/ui/sheet";
import { Link } from "@/i18n/navigation";
import { cn } from "@/lib/utils";
import { ApiError } from "@/lib/api";
import { generatePassword, generateUniqueId, normalizeUniqueId } from "@/lib/generate";
import { CompanySelect, StoreSelect, SupervisorSelect } from "@/components/org/entity-selects";
import { useCompanies } from "@/features/org/companies";
import { useStores } from "@/features/org/stores";
import {
  useCreateEmployee,
  useSupervisors,
  useUpdateEmployee,
} from "@/features/employees/employees";
import { useCurrentUser } from "@/features/session/use-current-user";
import { assignableRoles, ROLE_META } from "@/features/permissions/roles";
import {
  BENEFIT_ICONS,
  BENEFIT_OPTIONS,
  CONTRACT_TYPE_OPTIONS,
  EMPLOYEE_STATUS_OPTIONS,
  GENDER_OPTIONS,
  MARITAL_STATUS_OPTIONS,
  WORK_SCHEDULE_OPTIONS,
} from "@/features/employees/constants";
import type { MembershipRole } from "@/features/session/types";
import type { EmployeeBenefits, EmployeeDetail } from "@/features/employees/types";

const schema = z.object({
  // Step 1 — main data
  firstName: z.string().min(1, "Required"),
  lastName: z.string().min(1, "Required"),
  email: z.string().email("Invalid email").optional().or(z.literal("")),
  phone: z.string().optional(),
  nationality: z.string().optional(),
  dateOfBirth: z.string().optional(),
  gender: z.enum(["male", "female", "other", "prefer_not_to_say"]).optional().or(z.literal("")),
  maritalStatus: z
    .enum(["single", "married", "divorced", "widowed", "other"])
    .optional()
    .or(z.literal("")),
  idCardNumber: z.string().optional(),
  country: z.string().optional(),
  state: z.string().optional(),
  city: z.string().optional(),
  postalCode: z.string().optional(),
  address: z.string().optional(),
  iban: z.string().optional(),
  // Step 2 — contractual
  role: z.string().optional(),
  department: z.string().optional(),
  companyEmail: z.string().email("Invalid email").optional().or(z.literal("")),
  accountEmail: z.string().email("Invalid email").optional().or(z.literal("")),
  status: z.enum(["active", "invited", "on_leave", "suspended", "archived"]).optional(),
  workScheduleType: z
    .enum(["full_time", "part_time", "shift", "flexible", "remote"])
    .optional()
    .or(z.literal("")),
  weeklyHours: z
    .string()
    .optional()
    .refine((v) => !v || (Number(v) >= 0 && Number(v) <= 168), "0–168"),
  hireDate: z.string().optional(),
  contractEnd: z.string().optional(),
  contractType: z
    .enum(["full_time", "part_time", "temporary", "contractor", "intern"])
    .optional()
    .or(z.literal("")),
});
type Values = z.infer<typeof schema>;

const STEPS = [
  { label: "Main Data", hint: "Identity, address & ID" },
  { label: "Contractual Details", hint: "Role, contract & benefits" },
];

/** Fields validated on step 1 — gate "Next" on these. */
const STEP1_FIELDS = ["firstName", "lastName", "email"] as const;

export function EmployeeFormSheet({
  employee,
  trigger,
  open: openProp,
  onOpenChange,
  onDelete,
}: {
  employee?: EmployeeDetail;
  trigger?: ReactNode;
  open?: boolean;
  onOpenChange?: (open: boolean) => void;
  /** Edit mode only: open the delete modal (rendered by the parent). */
  onDelete?: () => void;
}) {
  const isEdit = Boolean(employee);
  const [openState, setOpenState] = useState(false);
  const open = openProp ?? openState;
  const setOpen = (next: boolean) => {
    setOpenState(next);
    onOpenChange?.(next);
  };
  const [step, setStep] = useState(0);
  const [serverError, setServerError] = useState<string | null>(null);
  const [primaryStoreId, setPrimaryStoreId] = useState<string | undefined>(
    employee?.primaryStoreId ?? undefined,
  );
  const [supervisorId, setSupervisorId] = useState<string | undefined>(
    employee?.supervisorId ?? undefined,
  );
  const [benefits, setBenefits] = useState<EmployeeBenefits>(employee?.benefits ?? {});
  // Unique ID + password — autogenerated, editable, regenerable (P14).
  const [uniqueId, setUniqueId] = useState(() => employee?.uniqueCode ?? generateUniqueId());
  const [password, setPassword] = useState(() => (employee ? "" : generatePassword()));
  // Platform login role — when set on create, provisions a login (pending approval).
  const [membershipRole, setMembershipRole] = useState<MembershipRole | "">(
    employee?.membershipRole ?? "",
  );

  const { data: stores } = useStores();
  const { data: companies } = useCompanies();
  const { data: supervisors } = useSupervisors();
  const { data: me } = useCurrentUser();
  const createEmployee = useCreateEmployee();
  const updateEmployee = useUpdateEmployee(employee?.id ?? "");

  // Company picker (enabled). In edit mode, moving to ANOTHER company isn't
  // allowed here — it must go through Transfers (notice shown below).
  const activeCompanyId = me?.companyId ?? companies?.[0]?.id;
  const [selectedCompanyId, setSelectedCompanyId] = useState<string | undefined>(
    employee?.companyId ?? activeCompanyId,
  );
  const movedCompany = isEdit && selectedCompanyId !== (employee?.companyId ?? activeCompanyId);

  // Roles this user may assign (strictly below their own). Platform users (super
  // admin etc.) may assign any tenant role.
  const roleOptions = (
    me?.platformRole ? (Object.keys(ROLE_META) as MembershipRole[]) : assignableRoles(me?.role)
  ).map((r) => ({ value: r, label: ROLE_META[r].label }));

  const {
    register,
    handleSubmit,
    reset,
    control,
    trigger: validate,
    formState: { errors, isSubmitting },
  } = useForm<Values>({
    resolver: zodResolver(schema),
    defaultValues: {
      firstName: employee?.firstName ?? "",
      lastName: employee?.lastName ?? "",
      email: employee?.email ?? "",
      phone: employee?.phone ?? "",
      nationality: employee?.nationality ?? "",
      dateOfBirth: employee?.dateOfBirth ?? "",
      gender: employee?.gender ?? "",
      maritalStatus: employee?.maritalStatus ?? "",
      idCardNumber: employee?.idCardNumber ?? "",
      country: employee?.country ?? "",
      state: employee?.state ?? "",
      city: employee?.city ?? "",
      postalCode: employee?.postalCode ?? "",
      address: employee?.address ?? "",
      iban: employee?.iban ?? "",
      role: employee?.role ?? "",
      department: employee?.department ?? "",
      companyEmail: employee?.companyEmail ?? "",
      accountEmail: employee?.companyEmail ?? "",
      status: employee?.status ?? "active",
      workScheduleType: employee?.workScheduleType ?? "",
      weeklyHours: employee?.weeklyHours != null ? String(employee.weeklyHours) : "",
      hireDate: employee?.hireDate ?? "",
      contractEnd: employee?.contractEnd ?? "",
      contractType: employee?.contractType ?? "",
    },
  });

  const resetAll = () => {
    reset();
    setStep(0);
    setPrimaryStoreId(employee?.primaryStoreId ?? undefined);
    setSupervisorId(employee?.supervisorId ?? undefined);
    setBenefits(employee?.benefits ?? {});
    setUniqueId(employee?.uniqueCode ?? generateUniqueId());
    setPassword(employee ? "" : generatePassword());
    setMembershipRole(employee?.membershipRole ?? "");
    setSelectedCompanyId(employee?.companyId ?? activeCompanyId);
    setServerError(null);
  };

  const goNext = async () => {
    const ok = await validate(STEP1_FIELDS);
    if (ok) setStep(1);
  };

  const toggleBenefit = (key: string) => setBenefits((b) => ({ ...b, [key]: !b[key] }));

  // The REAL persist — only ever invoked from the final step's submit button.
  const onSubmit = async (values: Values) => {
    setServerError(null);
    const payload = {
      firstName: values.firstName,
      lastName: values.lastName,
      email: values.email || undefined,
      phone: values.phone || undefined,
      companyEmail: values.companyEmail || undefined,
      nationality: values.nationality || undefined,
      dateOfBirth: values.dateOfBirth || undefined,
      gender: values.gender || undefined,
      maritalStatus: values.maritalStatus || undefined,
      idCardNumber: values.idCardNumber || undefined,
      iban: values.iban || undefined,
      country: values.country || undefined,
      state: values.state || undefined,
      city: values.city || undefined,
      postalCode: values.postalCode || undefined,
      address: values.address || undefined,
      role: values.role || undefined,
      department: values.department || undefined,
      status: values.status,
      workScheduleType: values.workScheduleType || undefined,
      weeklyHours: values.weeklyHours ? Number(values.weeklyHours) : undefined,
      hireDate: values.hireDate || undefined,
      contractEnd: values.contractEnd || undefined,
      contractType: values.contractType || undefined,
      primaryStoreId: primaryStoreId || undefined,
      supervisorId: supervisorId || undefined,
      benefits: Object.keys(benefits).length ? benefits : undefined,
      uniqueCode: uniqueId || undefined,
      // Platform login (create only) — assigning a role raises an activation request.
      ...(!isEdit && membershipRole
        ? {
            membershipRole,
            accountEmail: values.accountEmail || values.email || undefined,
          }
        : {}),
    };
    try {
      if (isEdit) await updateEmployee.mutateAsync(payload);
      else await createEmployee.mutateAsync(payload);
      setOpen(false);
      resetAll();
    } catch (error) {
      setServerError(error instanceof ApiError ? error.message : "Something went wrong.");
      setStep(1);
    }
  };

  // Hard guard: the form NEVER persists on its own. Enter on step 0 advances;
  // Enter on step 2 does nothing — saving happens ONLY via the Save button's
  // explicit onClick below. This kills any implicit/auto submit (a portaled
  // picker/select firing a stray submit) that previously saved + closed.
  const handleFormSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (step === 0) void goNext();
  };

  // Explicit save — wired to the Save button's onClick only.
  const handleSave = () => {
    void handleSubmit(onSubmit)();
  };

  return (
    <Sheet
      open={open}
      onOpenChange={(o) => {
        // Persist field data when the sheet closes (backdrop / X / Cancel) — it is
        // only reset when reopened fresh for a NEW employee. Edit reopens reseed
        // from the employee. This keeps work-in-progress across an accidental close
        // (lost only on route change / refresh).
        if (o && !openProp) resetAll();
        setOpen(o);
      }}
    >
      {trigger ? <SheetTrigger render={trigger as React.ReactElement} /> : null}
      <SheetContent
        showCloseButton={false}
        closeOnBackdrop
        className="flex w-full flex-col gap-0 p-0 data-[side=right]:sm:max-w-lg"
      >
        {/* Header — title + small subtext + step rail (heading UNDER the number).
            Medium close (✕) top-right. */}
        <div className="relative border-b border-border bg-linear-to-br from-accent-soft via-surface to-surface px-6 pt-4 pb-4">
          <button
            type="button"
            onClick={() => setOpen(false)}
            aria-label="Close"
            className="absolute top-4 right-4 inline-flex size-8 items-center justify-center rounded-lg text-muted-foreground transition-colors hover:bg-accent-soft hover:text-foreground"
          >
            <X className="size-5" />
          </button>
          <h2 className="font-display text-lg font-semibold text-foreground">
            {isEdit ? "Edit Employee" : "New Employee"}
          </h2>
          <p className="mt-0.5 text-xs text-muted-foreground">
            {isEdit
              ? "Update this person's main data and contractual details."
              : "Add a person to your directory — main data, then contractual details."}
          </p>
          <StepRail steps={STEPS} current={step} onStep={setStep} />
        </div>

        <form onSubmit={handleFormSubmit} className="flex min-h-0 flex-1 flex-col" noValidate>
          <div className="scrollbar-none flex-1 space-y-6 overflow-y-auto px-6 py-5">
            {step === 0 ? (
              <>
                <FieldGroup title="Main data">
                  <FormField
                    id="firstName"
                    label="First name"
                    error={errors.firstName?.message}
                    {...register("firstName")}
                  />
                  <FormField
                    id="lastName"
                    label="Last name"
                    error={errors.lastName?.message}
                    {...register("lastName")}
                  />
                  <FormField
                    id="email"
                    label="Email"
                    type="email"
                    error={errors.email?.message}
                    {...register("email")}
                  />
                  <FormField id="phone" label="Phone" {...register("phone")} />
                  <FullWidth>
                    <UniqueIdField
                      value={uniqueId}
                      onChange={setUniqueId}
                      onRegenerate={() => setUniqueId(generateUniqueId())}
                    />
                  </FullWidth>
                </FieldGroup>

                <FieldGroup title="Personal information">
                  <FormField id="nationality" label="Nationality" {...register("nationality")} />
                  <Controller
                    control={control}
                    name="dateOfBirth"
                    render={({ field }) => (
                      <DateField
                        id="dateOfBirth"
                        label="Date of birth"
                        value={field.value ?? ""}
                        onChange={field.onChange}
                      />
                    )}
                  />
                  <ControlledSelect
                    control={control}
                    name="gender"
                    label="Gender"
                    options={GENDER_OPTIONS}
                  />
                  <ControlledSelect
                    control={control}
                    name="maritalStatus"
                    label="Marital status"
                    options={MARITAL_STATUS_OPTIONS}
                  />
                  <FullWidth>
                    <FormField
                      id="idCardNumber"
                      label="ID card number"
                      placeholder="National ID / passport no."
                      {...register("idCardNumber")}
                    />
                  </FullWidth>
                </FieldGroup>

                <FieldGroup title="Address">
                  <Controller
                    control={control}
                    name="country"
                    render={({ field }) => (
                      <Field label="Country">
                        <CountrySelect value={field.value || undefined} onChange={field.onChange} />
                      </Field>
                    )}
                  />
                  <FormField id="state" label="State / region" {...register("state")} />
                  <FormField id="city" label="City" {...register("city")} />
                  <FormField id="postalCode" label="Postal code" {...register("postalCode")} />
                  <FullWidth>
                    <FormField id="address" label="Address" {...register("address")} />
                  </FullWidth>
                </FieldGroup>

                <FieldGroup title="Banking & accounts">
                  <FullWidth>
                    <FormField
                      id="iban"
                      label="IBAN"
                      placeholder="GB29 NWBK 6016 1331 9268 19"
                      {...register("iban")}
                    />
                  </FullWidth>
                  {isEdit ? (
                    <FullWidth>
                      <p className="text-xs text-muted-foreground">
                        Manage additional bank accounts from the employee&apos;s profile.
                      </p>
                    </FullWidth>
                  ) : null}
                </FieldGroup>
              </>
            ) : (
              <>
                <FieldGroup title="Platform information">
                  <FullWidth>
                    <Field label="Company">
                      <CompanySelect
                        companies={companies}
                        value={selectedCompanyId}
                        onChange={setSelectedCompanyId}
                      />
                    </Field>
                  </FullWidth>
                  {/* Edit mode: a different company can't be set here — that's a
                      transfer. Show a notice + a button into the Transfers module. */}
                  {movedCompany ? (
                    <FullWidth>
                      <div className="flex flex-col gap-2 rounded-lg border border-amber-300/60 bg-amber-50 px-3 py-2.5">
                        <p className="text-xs text-amber-800">
                          You can&apos;t transfer this user to another company from here. Use the
                          Transfers module to move them between companies.
                        </p>
                        <Link
                          href="/transfers"
                          className="inline-flex w-fit items-center gap-1.5 rounded-lg border border-amber-300 bg-white px-3 py-1.5 text-xs font-semibold text-amber-800 transition-colors hover:bg-amber-100"
                        >
                          <ArrowRightLeft className="size-3.5" />
                          Go to Transfers
                        </Link>
                      </div>
                    </FullWidth>
                  ) : null}
                  <FullWidth>
                    <Field label="Primary store">
                      <StoreSelect
                        stores={stores}
                        companies={companies}
                        value={primaryStoreId}
                        onChange={setPrimaryStoreId}
                      />
                    </Field>
                  </FullWidth>
                  <FullWidth>
                    <Field label="Supervisor">
                      <SupervisorSelect
                        supervisors={supervisors}
                        value={supervisorId}
                        onChange={setSupervisorId}
                      />
                    </Field>
                  </FullWidth>
                  {/* Platform role — assignable roles are strictly below the
                      creator's own (platform users may assign any). Creating with
                      a role provisions a login pending HR/admin activation. */}
                  {!isEdit ? (
                    <FullWidth>
                      <Field label="Platform role">
                        <OptionSelect
                          value={membershipRole || undefined}
                          onChange={(v) => setMembershipRole((v as MembershipRole) ?? "")}
                          options={roleOptions}
                          placeholder="No login (directory only)"
                        />
                        {membershipRole ? (
                          <div className="mt-2 flex items-start gap-2 rounded-lg border border-border bg-accent-soft/60 px-3 py-2 text-xs text-muted-foreground">
                            <ShieldCheck className="mt-0.5 size-3.5 shrink-0 text-primary" />
                            <span>
                              A login will be created as{" "}
                              <RoleTag role={membershipRole as MembershipRole} /> and sent for{" "}
                              <span className="font-medium text-foreground">HR/admin approval</span>.
                              The invite email is sent once approved.
                            </span>
                          </div>
                        ) : null}
                      </Field>
                    </FullWidth>
                  ) : (
                    <FullWidth>
                      <Field label="Platform role">
                        {employee?.membershipRole ? (
                          <div className="flex h-9 items-center">
                            <RoleTag role={employee.membershipRole} />
                          </div>
                        ) : (
                          <p className="flex h-9 items-center text-sm text-muted-foreground">
                            No portal login linked.
                          </p>
                        )}
                      </Field>
                    </FullWidth>
                  )}
                  <ControlledSelect
                    control={control}
                    name="status"
                    label="Status"
                    options={EMPLOYEE_STATUS_OPTIONS}
                  />
                  <FormField
                    id="companyEmail"
                    label="Company email"
                    type="email"
                    error={errors.companyEmail?.message}
                    {...register("companyEmail")}
                  />
                  {!isEdit && membershipRole ? (
                    <FullWidth>
                      <FormField
                        id="accountEmail"
                        label="Login email"
                        type="email"
                        placeholder="Defaults to the personal email"
                        error={errors.accountEmail?.message}
                        {...register("accountEmail")}
                      />
                    </FullWidth>
                  ) : null}
                  {!isEdit ? (
                    <FullWidth>
                      <PasswordField
                        value={password}
                        onChange={setPassword}
                        onRegenerate={() => setPassword(generatePassword())}
                      />
                    </FullWidth>
                  ) : null}
                </FieldGroup>

                <FieldGroup title="Contract information">
                  {/* Job role + Department live here (moved out of Platform). */}
                  <FormField id="role" label="Job role" placeholder="Barista" {...register("role")} />
                  <FormField
                    id="department"
                    label="Department"
                    placeholder="Operations"
                    {...register("department")}
                  />
                  <ControlledSelect
                    control={control}
                    name="workScheduleType"
                    label="Work schedule"
                    options={WORK_SCHEDULE_OPTIONS}
                  />
                  <FormField
                    id="weeklyHours"
                    type="number"
                    label="Weekly hours"
                    error={errors.weeklyHours?.message}
                    {...register("weeklyHours")}
                  />
                  <Controller
                    control={control}
                    name="hireDate"
                    render={({ field }) => (
                      <DateField
                        id="hireDate"
                        label="Hire date"
                        value={field.value ?? ""}
                        onChange={field.onChange}
                      />
                    )}
                  />
                  <Controller
                    control={control}
                    name="contractEnd"
                    render={({ field }) => (
                      <DateField
                        id="contractEnd"
                        label="Contract end"
                        value={field.value ?? ""}
                        onChange={field.onChange}
                      />
                    )}
                  />
                  <FullWidth>
                    <ControlledSelect
                      control={control}
                      name="contractType"
                      label="Contract type"
                      options={CONTRACT_TYPE_OPTIONS}
                    />
                  </FullWidth>
                </FieldGroup>

                <FieldGroup title="Benefits">
                  <FullWidth>
                    <div className="grid grid-cols-2 gap-2">
                      {BENEFIT_OPTIONS.map((b) => {
                        const on = Boolean(benefits[b.key]);
                        const Icon = BENEFIT_ICONS[b.key];
                        return (
                          <button
                            key={b.key}
                            type="button"
                            onClick={() => toggleBenefit(b.key)}
                            className={cn(
                              "flex items-center gap-2.5 rounded-lg border px-3 py-2 text-left text-sm transition-colors",
                              on
                                ? "border-primary bg-accent-soft text-foreground"
                                : "border-border bg-surface text-muted-foreground hover:border-foreground/20",
                            )}
                          >
                            <span
                              className={cn(
                                "flex size-7 shrink-0 items-center justify-center rounded-lg transition-colors",
                                on ? "bg-primary text-primary-foreground" : "bg-muted text-muted-foreground",
                              )}
                            >
                              {Icon ? <Icon className="size-4" /> : null}
                            </span>
                            <span className="flex-1">{b.label}</span>
                            {on ? <Check className="size-4 shrink-0 text-primary" /> : null}
                          </button>
                        );
                      })}
                    </div>
                  </FullWidth>
                </FieldGroup>
              </>
            )}

            {serverError ? <p className="text-sm text-destructive">{serverError}</p> : null}
          </div>

          {/* Footer — delete (left, edit only) · Cancel + Back/Next/Save (right). */}
          <div className="flex items-center justify-between gap-2 border-t border-border bg-surface-subtle/60 px-6 py-3">
            <div>
              {isEdit && onDelete ? (
                <Button
                  type="button"
                  variant="ghost"
                  onClick={onDelete}
                  className="text-destructive hover:bg-destructive/10 hover:text-destructive"
                >
                  <Trash2 />
                  Delete
                </Button>
              ) : null}
            </div>
            <div className="flex items-center gap-2">
              {step === 0 ? (
                <Button type="button" variant="outline" onClick={() => setOpen(false)}>
                  Cancel
                </Button>
              ) : (
                <Button type="button" variant="outline" onClick={() => setStep(0)}>
                  <ArrowLeft />
                  Back
                </Button>
              )}
              {step === 0 ? (
                <Button type="button" onClick={goNext}>
                  Next
                  <ArrowRight />
                </Button>
              ) : (
                <Button type="button" onClick={handleSave} disabled={isSubmitting}>
                  {isSubmitting ? "Saving…" : isEdit ? "Save changes" : "Create employee"}
                </Button>
              )}
            </div>
          </div>
        </form>
      </SheetContent>
    </Sheet>
  );
}

/** Step rail: numbered circles with the heading + tiny subtext UNDER each, a
 * connector line between that fills as you progress (P14). */
function StepRail({
  steps,
  current,
  onStep,
}: {
  steps: { label: string; hint: string }[];
  current: number;
  onStep: (i: number) => void;
}) {
  return (
    <ol className="mt-4 flex items-start">
      {steps.map((s, i) => {
        const done = i < current;
        const active = i === current;
        const isLast = i === steps.length - 1;
        return (
          <li key={s.label} className={cn("flex items-start", isLast ? "flex-none" : "flex-1")}>
            {/* Number + its heading/hint, stacked & center-aligned as one unit so
                the text sits directly UNDER the circle. */}
            <div className="flex w-max flex-col items-center">
              <button
                type="button"
                disabled={i > current}
                onClick={() => i < current && onStep(i)}
                className={cn(
                  "flex size-9 shrink-0 items-center justify-center rounded-full border-2 text-sm font-semibold transition-all",
                  active &&
                    "border-primary bg-primary text-primary-foreground shadow-[0_0_0_4px_rgb(var(--accent-soft))]",
                  done && "border-primary bg-accent-soft text-primary",
                  !active && !done && "border-border bg-surface text-muted-foreground",
                )}
              >
                {done ? <Check className="size-4" /> : i + 1}
              </button>
              <div className="mt-1.5 text-center">
                <p
                  className={cn(
                    "text-xs font-semibold whitespace-nowrap",
                    active || done ? "text-foreground" : "text-muted-foreground",
                  )}
                >
                  {s.label}
                </p>
                <p className="text-[10px] leading-tight whitespace-nowrap text-muted-foreground">
                  {s.hint}
                </p>
              </div>
            </div>
            {/* Connector to the next step — vertically aligned with the circle. */}
            {!isLast ? (
              <span
                className={cn(
                  "mt-[18px] h-0.5 flex-1 rounded-full transition-colors",
                  i < current ? "bg-primary" : "bg-border",
                )}
              />
            ) : null}
          </li>
        );
      })}
    </ol>
  );
}

/** Unique-ID field: uppercase-normalized input + "Generate new ID" text button. */
function UniqueIdField({
  value,
  onChange,
  onRegenerate,
}: {
  value: string;
  onChange: (v: string) => void;
  onRegenerate: () => void;
}) {
  return (
    <div className="space-y-1.5">
      <div className="flex items-center justify-between">
        <label htmlFor="uniqueId" className="text-[13px] font-medium text-foreground">
          Unique ID
        </label>
        <button
          type="button"
          onClick={onRegenerate}
          className="inline-flex items-center gap-1 text-xs font-medium text-primary hover:text-accent-strong"
        >
          <RefreshCw className="size-3" />
          Generate new ID
        </button>
      </div>
      <input
        id="uniqueId"
        value={value}
        onChange={(e) => onChange(normalizeUniqueId(e.target.value))}
        className="h-9 w-full rounded-lg border border-border bg-background px-3 text-sm font-mono tracking-wide text-foreground uppercase outline-none transition-colors focus-visible:border-ring focus-visible:ring-3 focus-visible:ring-ring/50"
        placeholder="ABC-123"
      />
    </div>
  );
}

/** Password field with a regenerate button (autogenerated, editable). */
function PasswordField({
  value,
  onChange,
  onRegenerate,
}: {
  value: string;
  onChange: (v: string) => void;
  onRegenerate: () => void;
}) {
  return (
    <div className="space-y-1.5">
      <div className="flex items-center justify-between">
        <label htmlFor="genPassword" className="text-[13px] font-medium text-foreground">
          Temporary password
        </label>
        <button
          type="button"
          onClick={onRegenerate}
          className="inline-flex items-center gap-1 text-xs font-medium text-primary hover:text-accent-strong"
        >
          <RefreshCw className="size-3" />
          Regenerate
        </button>
      </div>
      <input
        id="genPassword"
        value={value}
        onChange={(e) => onChange(e.target.value)}
        className="h-9 w-full rounded-lg border border-border bg-background px-3 font-mono text-sm text-foreground outline-none transition-colors focus-visible:border-ring focus-visible:ring-3 focus-visible:ring-ring/50"
        placeholder="Auto-generated"
      />
    </div>
  );
}

/** Small labeled wrapper for non-input controls (rich selects). */
function Field({ label, children }: { label: string; children: ReactNode }) {
  return (
    <div className="space-y-1.5">
      <label className="text-[13px] font-medium text-foreground">{label}</label>
      {children}
    </div>
  );
}

/** Labeled, RHF-controlled themed dropdown (OptionSelect) for the modal. */
function ControlledSelect({
  control,
  name,
  label,
  options,
  placeholder = "—",
}: {
  control: Control<Values>;
  name: keyof Values;
  label: string;
  options: { value: string; label: string }[];
  placeholder?: string;
}) {
  return (
    <Field label={label}>
      <Controller
        control={control}
        name={name}
        render={({ field }) => (
          <OptionSelect
            value={(field.value as string) || undefined}
            onChange={field.onChange}
            options={options}
            placeholder={placeholder}
          />
        )}
      />
    </Field>
  );
}
